.Dd August 30, 2009
.Dt APERTIUM-DESMEDIAWIKI 1
.Os Apertium
.Sh NAME
.Nm apertium-desmediawiki
.Nd MediaWiki format processor for Apertium
.Sh SYNOPSIS
.Nm apertium-desmediawiki
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-desmediawiki
is a processor for mediawiki XML dumps
(i.e., those produced using Special:Export).
Data should be passed through this processor before being piped to
.Xr lt-proc 1 .
The program takes input in the form of a text file
and produces output suitable for processing with
.Xr lt-proc 1 .
Format information (newlines, tabs, etc.) is enclosed in brackets so that
.Xr lt-proc 1
treats it as whitespace between words.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh EXAMPLES
You could write the following to show how the word
.Dq gener
is analysed:
.Dl echo Qo gener Qc | apertium-destxt | lt-proc ca-es.automorf.bin
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-deshtml 1 ,
.Xr apertium-desrtf 1 ,
.Xr apertium-destxt 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Complicated links \(en [[page|alternative text]], [[link]]s, etc. are not
supported.
.Pp
The mediawiki parser has special support for mixing apostrophes and
apostrophes as formatting.
This is not supported either.
