.TH apertium-gen-reformat 1 2006-03-21 "" ""
.SH NAME
apertium-gen-reformat \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
architecture: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-gen-reformat
[
.B \-O \fR
] <input file> <output file>
.PP
.SH DESCRIPTION
.BR apertium-gen-reformat 
is a script which generates a C++ reformatter for a particular format. The
reformatter reads in a format file in XML and outputs a C++ reformatter 
using flex.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH SEE ALSO
.I apertium-gen-deformat\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

