.TH apertium-postlatex-raw 1 2012-02-29 "" ""
.SH NAME
apertium-postlatex \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-postlatex-raw
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-postlatex-raw
This filter generates LaTeX code from the output of apertium-relatex
command. Non-ASCII characters are generated into its native encoding,
depending on the locale of the running environment.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH SEE ALSO
.I apertium-deslatex\fR(1),
.I apertium-prelatex\fR(1),
.I apertium-relatex\fR(1),
.I apertium-postlatex-raw\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Complicated constructions in LaTeX (i.e. custom defined tags) are not (yet)
supported.
.PP
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

