.Dd March 8, 2006
.Dt APERTIUM 1
.Os Apertium
.Sh NAME
.Nm apertium
.Nd machine translation application platform
.Sh SYNOPSIS
.Nm apertium
.Op Fl au
.Op Fl d Ar datadir
.Op Fl f Ar format
.Ar language-pair
.Op Ar infile Op Ar outfile
.Sh DESCRIPTION
.Nm apertium
is the application that most people will be using as it simplifies the
use of apertium/lt-toolbox tools for machine translation
purposes.
.Pp
This tool tries to ease the use of
.Em lt-toolbox
(which contains all the lexical processing modules and tools) and
.Em apertium
(which contains the rest of the engine)
by providing a unique front-end to the end-user.
.Pp
The different modules behind the apertium machine translation
architecture are in order:
.Bl -tag -width Ds
.It de-formatter
Separates the text to be translated from the format information.
.It morphological-analyser
Tokenizes the text in surface forms.
.It part-of-speech tagger
Chooses one surface forms among homographs.
.It lexical transfer module
Reads each source-language lexical form and delivers a corresponding
target-language lexical form.
.It structural transfer module
Detects fixed-length patterns of lexical forms (chunks or phrases)
needing special processing due to grammatical divergences
between the two languages and performs the corresponding transformations.
.It morphological generator
Delivers a target-language surface form for each target-language lexical form,
by suitably inflecting it.
.It post-generator
Performs orthographical operations such as contractions and apostrophations.
.It re-formatter
Restores the format information encapsulated by the de-formatter
into the translated text and removes the encapsulation sequences
used to protect certain characters in the source text.
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d Ar datadir
The directory holding the linguistic data.
By default it will use the expected installation path.
.It Ar language-pair
The language pair:
.Ar LANG1 Ns \(en Ns Ar LANG2
(for instance
.Dq es-ca
or
.Dq ca-es ) .
.It Fl f Ar format
Specifies the format of the input and output files which can have these values:
.Bl -tag -width Ds
.It Cm txt
.Sy (default value)
Input and output files are in text format.
.It Cm html
Input and output files are in
.Dq html
format.
This
.Dq html
is the one accepted by the vast majority of web browsers.
.It Cm html-noent
Input and output files are in
.Dq html
format,
but preserving native encoding characters rather than using HTML text entities.
.It Cm rtf
Input and output files are in
.Dq rtf
format.
The accepted
.Dq rtf
is the one generated by Microsoft WordPad and
Microsoft Office up to and including Office 97.
.El
.It Fl u
Disable marking of unknown words with the
.Ql *
character.
.It Fl a
Enable marking of disambiguated words with the
.Ql =
character.
.El
.Sh FILES
These are the two files that can be used with this command:
.Bl -tag -width Ds
.It Fl m Ar memory.tmx
use a translation memory to recycle translations
.It Fl o Ar direction
translation direction using the translation memory,
by default
.Dq direction
is used instead
.It Fl l
lists the available translation directions and exits direction typically,
.Ar LANG1 Ns \(en Ns Ar LANG2 ,
but see
.Pa modes.xml
in language data
.It Ar infile
Input file
.Po Dv stdin No by default Pc .
.It Ar outfile
Output file
.Po Dv stdout No by default Pc .
.El
.Sh SEE ALSO
.Xr apertium-tagger 1 ,
.Xr lt-comp 1 ,
.Xr lt-expand 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
