.TH apertium-transfer 1 2006-03-08 "" ""
.SH NAME
apertium-transfer \- This application is part of (
.B apertium
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-transfer
[\-n] trules preproc biltrans [input [output]]
.PP
.B apertium-transfer
trules preproc [input [output]]
.PP
.B apertium-transfer
\-x extended trules preproc biltrans [input [output]]
.PP
.B apertium-transfer
\-c trules preproc biltrans [input [output]]
.PP
.B apertium-transfer
\-t trules preproc biltrans [input [output]]
.SH DESCRIPTION
.BR apertium-transfer 
is the program that performs the transfer from input language
into output language. Normally this program will not be used independently, but in combination with other programs:
.PP
.RE
.SH FILES
These are the five files that can be used with this command:
.PP
.B trules
Transfer rules file
.PP
.B preproc    
Result of preprocess trules file
.PP
.B biltrans   
Bilingual letter transducer file
.PP
.B infile
Input file (stdin by default).
.PP
.B outfile
Output file (stdout by default).
.PP
\-.B \-b
\-input from lexical transfer (single level transfer only)
\-.PP
\-.B \-h
\-shows this message
\-.PP
.B -n
Do not use a bilingual dictionary to process the input.
.PP
.B  -x bindix  
extended mode with user dictionary
.PP
.B -c
case-sensitiveness while accessing bilingual dictionary
.PP
.B -t
trace mode: show rule numbers and matched content
.PP
.B -T
extended trace mode, for use with apertium-transfer-tools
.PP
.B -z
null-flushing output on
.PP
.SH SEE ALSO
.I apertium \fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

