.Dd March 21, 2006
.Dt APERTIUM-VALIDATE-TRANSFER 1
.Os Apertium
.Sh NAME
.Nm apertium-validate-transfer
.Nd structural transfer rule validator for Apertium
.Sh SYNOPSIS
.Nm apertium-validate-transfer
.Ar input_file
.Sh DESCRIPTION
.Nm apertium-validate-transfer
is a script that validates a set of structural transfer rules against
the apertium structural transfer rules DTD using the xmllint utility.
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
