.TH apertium-validate-dictionary 1 2006-03-21 "" ""
.SH NAME
apertium-validate-dictionary \- This application is part of 
(
.B apertium
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-validate-dictionary <input_file>
.SH DESCRIPTION
.BR apertium-validate-dictionary
is a script that validates a dictionary file against
the apertium DTD file for dictionaries using the xmllint utility.

.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

