.Dd December 22, 2022
.Dt APERTIUM-VALIDATE-CRX 1
.Os Apertium
.Sh NAME
.Nm apertium-validate-crx
.Nd capitalization restoration rule file validator for Apertium
.Sh SYNOPSIS
.Nm apertium-validate-crx
.Ar input_file
.Sh DESCRIPTION
.Nm apertium-validate-crx
is a script that validates a capitalization rule file against
the apertium DTD file for capitalization rule file using the
.Xr xmllint 1
utility.
.Sh COPYRIGHT
Copyright \(co 2022 Apertium
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
