.Dd March 11, 2006
.Dt APERTIUM-VALIDATE-POSTCHUNK 1
.Os Apertium
.Sh NAME
.Nm apertium-validate-postchunk
.Nd intermediate postchunk rule validator for Apertium
.Sh SYNOPSIS
.Nm apertium-validate-postchunk
.Ar input_file
.Sh DESCRIPTION
This is an intermediate tool from Apertium level 2 engine.
You should never have to use it independently.
.Pp
It is a script that validates a set of structural postchunk rules
against the apertium structural postchunk rules DTD using the
.Xr xmllint 1
utility.
.Sh OPTIONS
It has no options.
.Sh FILES
.Bl -tag -width Ds
.It Ar input_file
A
.Pa postchunk.xml
file
.It Pa postchunk.dtd
The DTD used to validate the input file.
.El
.Sh SEE ALSO
.Xr apertium-gen-modes 1 ,
.Xr apertium-gen-oldbil 1 ,
.Xr apertium-interchunk 1 ,
.Xr apertium-validate-interchunk 1 ,
.Xr apertium-validate-modes 1
.Sh COPYRIGHT
Copyright \(co 2005\(en2007 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
