.TH apertium-retxt 1 2006-03-21 "" ""
.SH NAME
apertium-retxt \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-retxt
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-retxt 
is a text format processor. It restores the original formatting
the text had (newlines, tabs, etc.) before being passed through the apertium-destxt deformatter.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH SEE ALSO
.I apertium-rehtml\fR(1),
.I apertium-rertf\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

