.Dd December 11, 2006
.Dt APERTIUM-GEN-LEXTORMONO 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-lextormono
.Nd monolingual dictionary generator for apertium-lextor
.Sh SYNOPSIS
.Nm apertium-gen-lextormono
.Cm lr | rl
.Ar input_file output_file
.Sh DESCRIPTION
.Nm apertium-gen-lextormono
is the application responsible for generating the monolingual
dictionary used by the lexical selection module to know about the
translation sense marks of each source language word.
.Sh OPTIONS
.Bl -tag -width Ds
.It Cm lr
The monolingual dictionary to generate is for left to right translation.
.It Cm rl
The monolingual dictionary to generate is for right to left translation.
.El
.Sh FILES
These are the kinds of files used with this tool:
.Bl -tag -width Ds
.It Ar input_file
A bilingual dictionary.
.It Ar output_file
A monolingual dictionary that for each word gives its translation
sense marks.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
