.Dd March 24, 2007
.Dt APERTIUM-TAGGER-APPLY-NEW-RULES 1
.Os Apertium
.Sh NAME
.Nm apertium-tagger-apply-new-rules
.Nd rule enforcer for Apertium
.Sh SYNOPSIS
.Nm apertium-tagger-apply-new-rules
.Fl i Ar input_file
.Fl o Ar output_file
.Fl x Ar rules_file
.Sh DESCRIPTION
.Nm apertium-tagger-apply-new-rules
is used to forbid and enforce rules
which are applied to the given HMM parameters.
.Pp
Note that the TSX file provided with
.Fl Fl tsxfile
.Em must
be equal, in terms of label definitions,
to the one used when training the HMM parameters that are to be modified.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl i , Fl Fl filein
Specify the file with the HMM parameter to process
.It Fl o , Fl Fl fileout
To specify the file to which the HMM will be written
.It Fl x , Fl Fl tsxfile
File containing the rules to apply
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-tagger 1
.Sh COPYRIGHT
Copyright \(co 2005\(en2007 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
