.Dd December 12, 2006
.Dt APERTIUM-GEN-WLIST-LEXTOR 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-wlist-lextor
.Nd word list generator for apertium-lextor
.Sh SYNOPSIS
.Nm apertium-gen-wlist-lextor
.Ar input_file output_file
.Sh DESCRIPTION
.Nm apertium-gen-wlist-lextor
is the application responsible for generating the list of words used by
.Xr apertium-lextor 1 .
.Sh OPTIONS
This tool currently has no options.
.Sh FILES
These are the kinds of files used with this tool:
.Bl -tag -width Ds
.It Ar input_file
is a lextor monolingual dictionary file generated with
.Xr apertium-gen-lextormono 1 .
These files usually have the extension
.Pa .dix .
.It Ar output_file
The file which gets the generated list of words.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
