.Dd March 21, 2006
.Dt APERTIUM-PRETRANSFER 1
.Os Apertium
.Sh NAME
.Nm apertium-pretransfer
.Nd multiword modifier for Apertium
.Sh SYNOPSIS
.Nm apertium-pretransfer
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-pretransfer
module applies some changes to multiwords (such as moving the lemma queue of
a multiword with inner inflection just after the lemma head).
If the input is not a multiword, it does not affect the output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n , Fl Fl no-surface-forms
assume no surface forms
.It Fl e , Fl Fl compounds
treat \(a~ as compound separator
.It Fl z , Fl Fl null-flush
null-flushing output on
.It Fl h , Fl Fl help
Display this help.
.El
.Sh EXAMPLES
You could write the following to show how the expression
.Dq trobant-lo a faltar
is analysed:
.Bd -literal
echo "trobant-lo a faltar" | apertium-destxt | lt-proc ca-es.automorf.bin \e
    |./ca-es.tagger --tagger ca-es | apertium-pretransfer
.Ed
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-destxt 1 ,
.Xr apertium-transfer 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
