.TH apertium-desmediawiki 1 2009-08-30 "" ""
.SH NAME
apertium-desmediawiki \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-desmediawiki
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-desmediawiki
is a processor for mediawiki XML dumps (i.e., those produced using 
Special:Export. Data should be passed through this 
processor before being piped to lt-proc. The program takes input
in the form of a text file and produces output suitable for
processing with lt-proc. Format information (newlines, tabs, etc.) is enclosed in brackets so that lt-proc treats it as whitespace between words.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH EXAMPLE
.TP
You could write the following to show how the word "gener" is analysed: 
.TP
echo "gener" | apertium-destxt | lt-proc ca-es.automorf.bin
.PP
.SH SEE ALSO
.I apertium-destxt\fR(1),
.I apertium-deshtml\fR(1),
.I apertium-desrtf\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Complicated links - [[page|alternative text]], [[link]]s, etc. are not
supported.
.PP
The mediawiki parser has special support for mixing apostrophes and 
apostrophes as formatting. This is not supported either.
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

