.Dd February 29, 2012
.Dt APERTIUM-PRELATEX 1
.Os Apertium
.Sh NAME
.Nm apertium-prelatex
.Nd LaTeX preprocessor for Apertium
.Sh SYNOPSIS
.Nm apertium-prelatex
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-prelatex
This filter preprocess LaTeX as input transforming it into a deformatted
.Dq XMLish
LaTeX custom format.
The output suitable for preprocess with
.Xr apertium-deslatex 1
deformatter.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-deslatex 1 ,
.Xr apertium-postlatex 1 ,
.Xr apertium-postlatex-raw 1 ,
.Xr apertium-relatex 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Complicated constructions in LaTeX (e.g., custom defined tags) are not (yet)
supported.
