.Dd December 12, 2006
.Dt APERTIUM-LEXTOR 1
.Os Apertium
.Sh NAME
.Nm apertium-lextor
.Nd lexical selector module trainer for Apertium
.Sh SYNOPSIS
.Nm apertium-lextor
.Fl Fl trainwrd Ar stopwords words n left right corpus model
.Op Fl Fl weightexp Ar w
.Op Fl Fl debug
.Nm apertium-lextor
.Fl Fl trainlch
.Ar stopwords lexchoices n left right corpus wordmodel dic bildic model
.Op Fl Fl weightexp Ar w
.Op Fl Fl debug
.Nm apertium-lextor
.Fl Fl lextor Ar model dic left right
.Op Fl Fl debug
.Op Fl Fl weightexp Ar w
.Sh DESCRIPTION
.Nm apertium-lextor
is the application responsible for training and usage of the
.Em lexical selector module .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl t , Fl Fl trainwrd
Train word co-occurrences model.
It needs the following required parameters:
.Bl -tag -width Ds
.It Ar stopwords
file containing a list of stop words.
Stop words are ignored.
.It Ar words
file containing a list of words.
For each word a co-occurrence model is built.
.It Ar n
number of words per co-occurrence model (for each model, the
.Ar n
most frequent words).
.It Ar left
left-side context to take into account (number of words).
.It Ar right
right-side context to take into account (number of words).
.It Ar corpus
file containing the training corpus.
.It Ar model
output file on which the co\-occurrence models are saved.
.El
.It Fl r , Fl Fl trainlch
Train lexical choices co-occurrence models using a target language
co-occurrence model and a bilingual dictionary.
It needs the following required parameters:
.Bl -tag -width Ds
.It Ar stopwords
file containing a list of stop words.
Stop words are ignored.
.It Ar lexchoices
file containing a list of lexical choices.
For each lexical choice a co-occurrence model is built.
.It Ar n
number of words per co-occurrence model (for each model, the
.Ar n
most frequent words).
.It Ar left
left-side context to take into account (number of words).
.It Ar right
right-side context to take into account (number of words).
.It Ar corpus
file containing the training corpus.
.It Ar wordmodel
target-language word co-occurrence model (previously trained by means of the
.Fl Fl trainwrd
option).
.It Ar dic
the lexical-selection dictionary (binary format).
.It Ar bildic
the bilingual dictionary (binary format).
.It Ar model
output file on which the co-occurrence models are saved.
.El
.It Fl l , Fl Fl lextor
Perform the lexical selection on the input stream.
It needs the following required parameters:
.Bl -tag -width Ds
.It Ar model
file containing the model to be used for the lexical selection.
.It Ar dic
lexical-selection dictionary (binary format).
.It Ar left
left-side context to take into account (number of words).
.It Ar right
right-side context to take into account (number of words).
.El
.It Fl Fl weightexp Ar w
Specify a weight value to change the influence of surrounding words
while training or performing the lexical selection.
The parameter
.Ar w
must be a positive value.
.It Fl d , Fl Fl debug
Show debug information while working.
.It Fl h , Fl Fl help
Shows this help.
.It Fl v , Fl Fl version
Shows license information.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
