.TH apertium 1 2006-03-08 "" ""
.SH NAME
apertium \- This application is part of (
.B apertium
)
.PP
This tool is part of the apertium machine translation
architecture: \fBhttp://apertium.sf.net\fR.
.SH SYNOPSIS
.B apertium
[-d datadir] [-f format] [-u] [-a] {language-pair} [infile [outfile]]
.SH DESCRIPTION
.BR apertium 
is the application that most people will be using as it simplifies the
use of apertium/lt-toolbox tools for machine translation
purposes. 
.PP
This tool tries to ease the use of \fIlt-toolbox\fR (which contains
all the lexical processing modules and tools) and \fIapertium\fR
(which contains the rest of the engine) by providing a unique
front-end to the end-user.
.PP
The different modules behind the apertium machine translation
architecture are in order:
.RS
\(bu \fIde-formatter:\fR Separates the text to be translated from the
format information.
.PP
\(bu \fImorphological-analyser:\fR Tokenizes the text in surface forms.
.PP
\(bu \fIpart-of-speech tagger:\fR Chooses one surface forms among
homographs.
.PP
\(bu \fIlexical transfer module:\fR Reads each source-language lexical
form and delivers a corresponding target-language lexical form.
.PP
\(bu \fIstructural transfer module:\fR Detects fixed-length patterns
of lexical forms (chunks or phrases) needing special processing due to
grammatical divergences between the two languages and performs the
corresponding transformations.
.PP
\(bu \fImorphological generator:\fR Delivers a target-language surface
form for each target-language lexical form, by suitably inflecting it.
.PP
\(bu \fIpost-generator:\fR Performs orthographical operations such as
contractions and apostrophations.
.PP
\(bu \fIre-formatter:\fR Restores the format information encapsulated
by the de-formatter into the translated text and removes the
encapsulation sequences used to protect certain characters in the
source text.
.RE
.SH OPTIONS
.PP
.B -d datadir
The directory holding the linguistic data.  By default it will used the
expected installation path.
.PP
.B language-pair
The language pair: LANG1-LANG2 (for instance \fIes-ca\fR or \fIca-es\fR).
.PP
.B -f format
Specifies the format of the input and output files which can have
these values:
.RS
\(bu \fItxt\fR \fB(default value)\fR Input and output files are in
text format.
.PP
\(bu \fIhtml\fR Input and output files are in "html" format. This
"html" is the one accepted by the vast majority of web browsers.
.PP
\(bu \fIhtml-noent\fR Input and output files are in "html" format, but
preserving native encoding characters rather than using HTML text
entities.
.PP
\(bu \fIrtf\fR Input and output files are in "rtf" format. The
accepted "rtf" is the one generated by \fBMicrosoft WordPad (C)\fR and
\fBMicrosoft Office (C)\fR up to and including \fBOffice-97\fR.
.RE
.PP
.B -u
Disable marking of unknown words with the '*' character.
.PP
.B -a
Enable marking of disambiguated words with the '=' character.
.RS
.SH FILES
These are the two files that can be used with this command:
.PP
.B -m memory.tmx
use a translation memory to recycle translations
.PP
.B -o direction 
translation direction using the translation memory, by default 'direction' is used instead
.PP
.B -l
lists the available translation directions and exits direction        
typically, LANG1-LANG2, but see modes.xml in language data
.PP
.B infile
Input file (stdin by default).
.PP
.B outfile
Output file (stdout by default).
.PP
.SH SEE ALSO
.I lt-proc\fR(1),
.I lt-comp\fR(1),
.I lt-expand\fR(1),
.I apertium-tagger\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
(c) 2005,2006 Universitat d'Alacant / Universidad de Alicante. All rights
reserved.
