.TH apertium-pretransfer 1 2006-03-21 "" ""
.SH NAME
apertium-pretransfer \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-pretransfer
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-pretransfer 
module applies some changes to multiwords (such as moving the lemma queue of 
a multiword with inner inflection just after the lemma head). If 
the input is not a multiword, it does not affect the output.
.SH OPTIONS
.TP
.B \-n, \-\-no\-surface\-forms
assume no surface forms
.B \-e, \-\-compounds
treat ~ as compound separator
.B \-z, \-\-null\-flush
null-flushing output on
.B \-h, \-\-help
Display this help.
.PP
.SH EXAMPLE
.TP
You could write the following to show how the expression "trobant-lo a faltar" is analysed: 
.TP
echo "trobant-lo a faltar" | apertium-destxt | lt-proc ca-es.automorf.bin |./ca-es.tagger \-\-tagger ca-es | apertium-pretransfer
.PP
.SH SEE ALSO
.I apertium-destxt\fR(1),
.I apertium-transfer\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

