.TH apertium-desodt 1 2006-03-21 "" ""
.SH NAME
apertium-desodt \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-desodt
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-desodt 
is an ODT format processor. Data should be passed through this 
processor before being piped to lt-proc. The program takes input
in the form of an ODT document and produces output suitable for
processing with lt-proc. ODT tags and other format information are  enclosed in brackets so that lt-proc treats them as whitespace between words.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH EXAMPLE
.TP
You could write the following to show how the word "gener" is analysed: 
.TP
echo "<b>gener</b>" | apertium-desodt | lt-proc ca-es.automorf.bin
.PP
.SH SEE ALSO
.I apertium-destxt\fR(1),
.I apertium-desrtf\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

