.TH apertium-filter-ambiguity 1 2006-03-21 "" ""
.SH NAME
apertium-filter-ambiguity \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-filter-ambiguity
[input_file [output_file]]
.PP
.SH DESCRIPTION
.BR apertium-filter-ambiguity 
takes input from STDIN or input_file, gets tagger data, filters ambiguity 
classes and outputs on STDOUT or output_file, in each case.
.PP
.SH SEE ALSO
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

