.Dd March 8, 2006
.Dt APERTIUM-TRANSFER 1
.Os Apertium
.Sh NAME
.Nm apertium-transfer
.Nd language transfer program for Apertium
.Sh SYNOPSIS
.Nm apertium-transfer
.Op Fl n Ar trules preproc biltrans Op Ar input Op Ar output
.Nm apertium-transfer
.Ar trules preproc Op Ar input Op Ar output
.Nm apertium-transfer
.Fl x Ar extended trules preproc biltrans Op Ar input Op Ar output
.Nm apertium-transfer
.Fl c Ar trules preproc biltrans Op Ar input Op Ar output
.Nm apertium-transfer
.Fl t Ar trules preproc biltrans Op Ar input Op Ar output
.Sh DESCRIPTION
.Nm apertium-transfer
is the program that performs the transfer from input language
into output language.
Normally this program will not be used independently,
but in combination with other programs.
.Sh FILES
These are the five files that can be used with this command:
.Bl -tag -width Ds
.It Ar trules
Transfer rules file
.It Ar preproc
Result of preprocess trules file
.It Ar biltrans
Bilingual letter transducer file
.It Ar infile
Input file (stdin by default).
.It Ar outfile
Output file (stdout by default).
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n
Do not use a bilingual dictionary to process the input.
.It Fl x Ar bindix
extended mode with user dictionary
.It Fl c
case-sensitiveness while accessing bilingual dictionary
.It Fl t
trace mode: show rule numbers and matched content
.It Fl T
extended trace mode, for use with apertium-transfer-tools
.It Fl z
null-flushing output on
.El
.Sh SEE ALSO
.Xr apertium 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
