.Dd February 29, 2012
.Dt APERTIUM-DESLATEX 1
.Os Apertium
.Sh NAME
.Nm apertium-deslatex
.Nd LaTeX format processor for Apertium
.Sh SYNOPSIS
.Nm apertium-deslatex
.Op Fl hin
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
This tool is part of
.Lk https://www.apertium.com/ the Apertium open-source machine translation \
toolbox .
.Pp
The
.Nm apertium-deslatex
filter preprocesses
.Xr apertium-prelatex 1
output to a deformatted
.Dq XMLish
LaTeX custom format.
The output is suitable for processing with
.Xr lt-proc 1 .
Format information (newlines, tabs, etc.) is enclosed in brackets so that
.Xr lt-proc 1
treats it as whitespace between words.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.It Fl i
Makes the addition of trailing sentence terminator
.Pq Ql \&.
unconditional, often leading to duplicates.
.It Fl n
Suppresses the addition of a trailing sentence terminator.
.El
.Sh EXAMPLES
You could write the following to show how the word
.Dq gener
is analysed:
.Dl echo Qo <textit/><CONTENTS>gener</CONTENTS> Qc | apertium-deslatex | \
lt-proc ca-es.automorf.bin
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-destxt 1 ,
.Xr apertium-postlatex 1 ,
.Xr apertium-postlatex-raw 1 ,
.Xr apertium-prelatex 1 ,
.Xr apertium-relatex 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Complicated constructions in LaTeX (e.g., custom defined tags) are not (yet)
supported.
