.TH apertium-relatex 1 2012-02-29 "" ""
.SH NAME
apertium-relatex \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-relatex
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-relatex
This filter preprocess apertium generator output and removes superblanks
marks to do subsequent processing in apertium pipeline.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH SEE ALSO
.I apertium-destxt\fR(1),
.I apertium-prelatex\fR(1),
.I apertium-postlatex\fR(1),
.I apertium-desatex\fR(1),
.I apertium-postlatex-raw\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Complicated constructions in LaTeX (i.e. custom defined tags) are not (yet)
supported.
.PP
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

