.Dd March 21, 2006
.Dt APERTIUM-VALIDATE-TAGGER 1
.Os Apertium
.Sh NAME
.Nm apertium-validate-tagger
.Nd transition rule validator for Apertium
.Sh SYNOPSIS
.Nm apertium-validate-tagger
.Ar input_file
.Sh DESCRIPTION
.Nm apertium-validate-tagger
is a script that checks the validity of a set of rules which enforce the state
to state transition probabilities used by the part-of-speech tagger.
The script uses
.Xr xmllint 1
to validate against a DTD.
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
