.TH apertium-validate-tagger 1 2006-03-21 "" ""
.SH NAME
apertium-validate-tagger \- This application is part of 
(
.B apertium
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-validate-tagger <input_file>
.SH DESCRIPTION
.BR apertium-validate-tagger
is a script that checks the validity of a set of rules which 
enforce the state to state transition probabilities used by the 
part-of-speech tagger. The script uses xmllint to validate
against a DTD.

.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

