.TH apertium-rexlsx 1 2006-03-21 "" ""
.SH NAME
apertium-rexlsx \- This application is part of (
.B apertium 
)
.PP
This tool is part of the apertium open-source machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-rexlsx
[ <input file> [ <output file> ] ]
.PP
.SH DESCRIPTION
.BR apertium-rexlsx 
is an XLSX format processor. It restores the original XLSX formatting
the text had before being passed through the apertium-desxlsx deformatter.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help.
.PP
.SH SEE ALSO
.I apertium-retxt\fR(1),
.I apertium-rertf\fR(1),
.I lt-proc\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

