.Dd March 21, 2006
.Dt APERTIUM-RETXT 1
.Os Apertium
.Sh NAME
.Nm apertium-remediawiki
.Nd MediaWiki format processor for Apertium
.Sh SYNOPSIS
.Nm apertium-retxt
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-retxt
is a mediawiki format processor.
It restores the original formatting the text had (newlines, tabs, etc.)
before being passed through the
.Xr apertium-desmediawiki 1
deformatter.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-rehtml 1 ,
.Xr apertium-rertf 1 ,
.Xr apertium-retxt 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
