.Dd December 12, 2006
.Dt APERTIUM-GEN-WLIST-LEXTOR-TRANSLATION 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-wlist-lextor-translation
.Nd polysemous word translation generator for Apertium
.Sh SYNOPSIS
.Nm apertium-gen-wlist-lextor-translation
.Op Fl b Ar bi_dictionary |
.Op Fl m Ar mono_dictionary |
.Op Fl w Ar wordlist_file
.Sh DESCRIPTION
.Nm apertium-gen-wlist-lextor-translation
is the application responsible for generating all the possible
translations of polysemous words.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl m Ar dic.bin , Fl Fl mono Ar dic.bin
Specifies the monolingual lexical selection dictionary to use (see
.Xr apertium-gen-lextormono 1 ) .
.It Fl b Ar bildic.bin , Fl Fl bil Ar bildic.bin
Specifies the bilingual lexical selection ditionary to use (see
.Xr apertium-gen-lextorbil 1 ) .
.It Fl w Ar wlistfile , Fl Fl wlist Ar wlistfile
Specifies the list of words to translate (see
.Xr apertium-gen-wlist-lextor 1 ) .
.It Fl h , Fl Fl help
Shows a brief usage help.
.It Fl v , Fl Fl version
Shows the version string of this tool and its license.
.El
.Sh FILES
This tool uses no files apart from the ones associated with each option.
.Sh SEE ALSO
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-lextor 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
