.Dd December 12, 2006
.Dt APERTIUM-PREPROCESS-CORPUS-LEXTOR 1
.Os Apertium
.Sh NAME
.Nm apertium-preprocess-corpus-lextor
.Nd training corpus preprocessor for apertium-lextor
.Sh SYNOPSIS
.Nm apertium-preprocess-corpus-lextor
.Ar data_dir translation_dir input_file output_file
.Sh DESCRIPTION
.Nm apertium-preprocess-corpus-lextor
is the application responsible for preprocessing the training corpus
for the lexical selector training.
.Sh OPTIONS
This tool currently has no options.
.Sh FILES
These are the kinds of files and directories used with this tool:
.Bl -tag -width Ds
.It Ar data_dir
the path to the linguistic data to use.
.It Ar translation_dir
the translation direction to use.
.It Ar input_file
contains a large corpus in
.Pa raw
format.
.It Ar output_file
The file which gets the preprocessed corpus.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextor-eval 1 ,
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
