.Dd February 29, 2012
.Dt APERTIUM-POSTLATEX-RAW 1
.Os Apertium
.Sh NAME
.Nm apertium-postlatex-raw
.Nd LaTeX code generator for Apertium
.Sh SYNOPSIS
.Nm apertium-postlatex-raw
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-postlatex-raw
This filter generates LaTeX code from the output of
.Xr apertium-relatex 1
command.
Non-ASCII characters are generated into its native encoding,
depending on the locale of the running environment.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-deslatex 1 ,
.Xr apertium-prelatex 1 ,
.Xr apertium-relatex 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Complicated constructions in LaTeX (e.g., custom defined tags) are not (yet)
supported.
