.Dd December 12, 2006
.Dt APERTIUM-GEN-STOPWORDS-LEXTOR 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-stopwords-lextor
.Nd stopwords list generator for apertium-lextor
.Sh SYNOPSIS
.Nm apertium-gen-stopwords-lextor
.Ar n input_file output_file
.Sh DESCRIPTION
.Nm apertium-gen-stopwords-lextor
is the application responsible for generating the list of
.Em stopwords
used by the lexical selection module
.Pq Xr apertium-lextor 1 .
Stopwords are ignored as they cannot have multiple translations.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl Ar n
the desired number of stopwords.
.El
.Sh FILES
These are the kinds of parameters and files used with this tool:
.Bl -tag -width Ds
.It Ar input_file
contains a large preprocessed corpus (see
.Xr apertium-preprocess-corpus-lextor 1 ) .
.It Ar output_file
The file which gets the generated stopwords.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextorbil 1 ,
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
