.Dd March 21, 2006
.Dt APERTIUM-FILTER-AMBIGUITY 1
.Os Apertium
.Sh NAME
.Nm apertium-filter-ambiguity
.Nd ambiguity class filter for Apertium
.Sh SYNOPSIS
.Nm apertium-filter-ambiguity
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-filter-ambiguity
takes input from
.Dv stdin
or
.Ar input_file ,
gets tagger data, filters ambiguity classes and outputs on
.Dv STDOUT
or
.Ar output_file ,
in each case.
.Sh SEE ALSO
.Xr apertium 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
