.TH apertium-preprocess-transfer 1 2006-03-08 "" ""
.SH NAME
apertium-preprocess-transfer \- This application is part of (
.B apertium
)
.PP
This tool is part of the open-source apertium machine translation
toolbox: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium-preprocess-transfer
rules_file transfer_file
.SH DESCRIPTION
.BR apertium-preprocess-transfer 
is a structural transfer preprocessor which reads in a structural transfer 
rule file and generates a file with precompiled patterns and indexes to the 
actions of the rules of the structural transfer module specification.
.PP
.RE
.SH FILES
These are the two files that can be used with this command:
.PP
.B rules_file
File with structural transfer rules
.PP
.B transfer_file
File with precompiled patterns
.PP
.SH SEE ALSO
.I apertium\fR(1),
.I apertium-transfer\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
Copyright (c) 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.  You may redistribute copies of it under the terms
of the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.

