.Dd March 21, 2006
.Dt APERTIUM-VALIDATE-DICTIONARY 1
.Os Apertium
.Sh NAME
.Nm apertium-validate-dictionary
.Nd dictionary file validator for Apertium
.Sh SYNOPSIS
.Nm apertium-validate-dictionary
.Ar input_file
.Sh DESCRIPTION
.Nm apertium-validate-dictionary
is a script that validates a dictionary file against
the apertium DTD file for dictionaries using the
.Xr xmllint 1
utility.
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
