.Dd December 11, 2006
.Dt APERTIUM-GEN-LEXTORBIL 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-lextorbil
.Nd bilingual dictionary generator for apertium-lextor
.Sh SYNOPSIS
.Nm apertium-gen-lextorbil
.Cm lr | rl
.Ar input_file output_file
.Sh DESCRIPTION
.Nm apertium-gen-lextorbil
is the application responsible for generating the bilingual dictionary
used by the transfer module when
.Xr apertium-lextor 1
is being used to perform lexical selection.
.Sh OPTIONS
.Bl -tag -width Ds
.It Cm lr
The bilingual dictionary to generate is for left to right translation.
.It Cm rl
The bilingual dictionary to generate is for right to left translation.
.El
.Sh FILES
These are the kinds of files used with this tool:
.Bl -tag -width Ds
.It Ar input_file
A bilingual dictionary.
.It Ar output_file
A bilingual dictionary in which each word has
.Em only
one translation equivalent.
.El
.Sh SEE ALSO
.Xr apertium-gen-lextormono 1 ,
.Xr apertium-gen-stopwords-lextor 1 ,
.Xr apertium-gen-wlist-lextor 1 ,
.Xr apertium-gen-wlist-lextor-translation 1 ,
.Xr apertium-lextor 1 ,
.Xr apertium-lextor-eval 1 ,
.Xr apertium-preprocess-corpus-lextor 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
