.Dd March 21, 2006
.Dt APERTIUM-GEN-REFORMAT 1
.Os Apertium
.Sh NAME
.Nm apertium-gen-reformat
.Nd C++ reformatter generator for Apertium
.Sh SYNOPSIS
.Nm apertium-gen-reformat
.Op Fl O
.Ar input_file output_file
.Sh DESCRIPTION
.Nm apertium-gen-reformat
is a script which generates a C++ reformatter for a particular format.
The reformatter reads in a format file in XML
and outputs a C++ reformatter using
.Xr flex 1 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-gen-deformat 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
