.Dd March 21, 2006
.Dt APERTIUM-RERTF 1
.Os Apertium
.Sh NAME
.Nm apertium-rertf
.Nd Rich Text Format processor for Apertium
.Sh SYNOPSIS
.Nm apertium-rertf
.Op Ar input_file Op Ar output_file
.Sh DESCRIPTION
.Nm apertium-rertf
is an RTF format processor.
It restores the original RTF formatting the text had
before being passed through the
.Xr apertium-desrtf 1
deformatter.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display this help.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-rehtml 1 ,
.Xr apertium-retxt 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
